"""Made tag names unique

Revision ID: 6bd5a28e9f3e
Revises: da0e188568db
Create Date: 2024-11-06 19:40:37.767629

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '6bd5a28e9f3e'
down_revision = 'da0e188568db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tags', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Tags_name'), ['name'])

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_Users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_Users_email'), type_='unique')

    with op.batch_alter_table('Tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Tags_name'), type_='unique')

    # ### end Alembic commands ###
