"""Added User image and description

Revision ID: 6be33074b741
Revises: 6bd5a28e9f3e
Create Date: 2024-11-09 11:47:07.230779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be33074b741'
down_revision = '6bd5a28e9f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('profile_url')

    # ### end Alembic commands ###
