"""Created Liked and Tagged entries

Revision ID: da0e188568db
Revises: 
Create Date: 2024-11-06 18:19:01.143415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0e188568db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LikedEntries',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meme_id', sa.Integer(), nullable=False),
    sa.Column('liked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meme_id'], ['Memes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'meme_id')
    )
    op.create_table('TagEntries',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('meme_id', sa.Integer(), nullable=False),
    sa.Column('tagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meme_id'], ['Memes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['Tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'meme_id')
    )
    with op.batch_alter_table('Memes', schema=None) as batch_op:
        batch_op.drop_column('username')
        batch_op.drop_column('tags')
        batch_op.drop_column('liked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Memes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked', sa.VARCHAR(length=10000), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=1000), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=150), nullable=True))

    op.drop_table('TagEntries')
    op.drop_table('LikedEntries')
    op.drop_table('Tags')
    # ### end Alembic commands ###
