"""User created_at and Nullability changes

Revision ID: de408b9a95c7
Revises: f8f8ee8569fb
Create Date: 2025-09-20 23:00:56.279388

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, UTC


# revision identifiers, used by Alembic.
revision = 'de408b9a95c7'
down_revision = 'f8f8ee8569fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LikedEntries', schema=None) as batch_op:
        batch_op.alter_column('liked_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('Memes', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('TagEntries', schema=None) as batch_op:
        batch_op.alter_column('tagged_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('Tags', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        
    with op.batch_alter_table('Users', schema=None) as batch_op:
        current_time = datetime.now(UTC).isoformat()
        batch_op.execute(f"UPDATE Users SET created_at = '{current_time}'")
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('Tags', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)

    with op.batch_alter_table('TagEntries', schema=None) as batch_op:
        batch_op.alter_column('tagged_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('Memes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)

    with op.batch_alter_table('LikedEntries', schema=None) as batch_op:
        batch_op.alter_column('liked_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
