"""Added Username colour

Revision ID: f8f8ee8569fb
Revises: 6be33074b741
Create Date: 2024-11-14 20:33:11.095232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f8ee8569fb'
down_revision = '6be33074b741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username_colour', sa.String(length=7), server_default='#ffffff', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('username_colour')

    # ### end Alembic commands ###
